### PR TITLE
ported to Grails-3.0.1

### PR DESCRIPTION
**Pull request by puneetbehl**
@jeffbrown please merge this into master I've  upgraded the plugin to Grails-3.0.1

### CODE REVIEW

**Comment by puneetbehl** [comment]
@jeffbrown Any updates?

**Comment by jeffbrown** [comment]
@puneetbehl - I will look at it.  Thanks for the help.

**Comment by jeffbrown** [comment]
Would you mind changing the version number to 2.0-SNAPSHOT resubmitting this agains the 2.x branch?  I realize that there was never a 1.0 release but there could be and it may as well be for Grails 2 if that happens.  I think calling the new plugin 2.x makes sense.

**Comment by jeffbrown** [comment]
I have pulled this code onto the 2.x branch and will work on getting it published.  Thanks for the help.

**Comment by jeffscottbrown** [comment]
All of the ClojureProxyTests tests are failing:

```
./gradlew check
```

**Comment by jeffscottbrown** [comment]
https://github.com/grails-plugins/clojure/commit/cf49d419dba0a726a4f1761a8ed1348589e57002

**Pull request closed without merging**
